### ISSUE TITLE
Socket.pair doesn't seem to work in RBX

### ISSUE THREAD

**Issue by asppsa** [rubysl/rubysl-socket#8]
I was attempting to follow the example [here](http://ruby-doc.org/stdlib-1.9.3/libdoc/socket/rdoc/Socket.html#method-c-pair) for creating a pair of sockets that talk to each other.  This works in MRI, but in RBX I get this error:

~~~
TypeError: Tried to use non-reference value 0x14d46 as type Bignum (10)
	from /home/asp/rbx-dbg/gems/gems/rubysl-socket-2.0.1/lib/rubysl/socket.rb:988:in `socketpair'
	from kernel/platform/pointer.rb:306:in `new'
	from /home/asp/rbx-dbg/gems/gems/rubysl-socket-2.0.1/lib/rubysl/socket.rb:987:in `pair (socketpair)'
	from (irb):4
	from kernel/common/block_environment.rb:53:in `call_on_instance'
	from kernel/common/eval.rb:176:in `eval'
	from kernel/common/kernel.rb:511:in `loop'
	from kernel/bootstrap/proc.rb:20:in `call'
	from kernel/common/throw_catch.rb:30:in `catch'
	from kernel/common/throw_catch.rb:8:in `register'
	from kernel/common/throw_catch.rb:29:in `catch'
	from kernel/bootstrap/proc.rb:20:in `call'
	from kernel/common/throw_catch.rb:30:in `catch'
	from kernel/common/throw_catch.rb:8:in `register'
	from kernel/common/throw_catch.rb:29:in `catch'
	from kernel/delta/code_loader.rb:66:in `load_script'
	from kernel/delta/code_loader.rb:152:in `load_script'
	from kernel/loader.rb:656:in `script'
	from kernel/loader.rb:810:in `main'
~~~

Steps to reproduce (I guess this is a *nix only bug):

~~~ ruby
require 'socket'
Socket.pair(:UNIX, :STREAM, 0)
~~~

`UNIXSocket.pair` works, so this is not an urgent problem!

**Comment by YorickPeterse** [comment]
Fixed by https://github.com/rubysl/rubysl-socket/pull/9
